# Data Processing
imgH: 32 # the height of the input image
imgW: 100 # the width of the input image

# Model Architecture
num_fiducial: 20 # number of fiducial points of TPS-STN"
input_channel: 3 # the number of input channel of Feature extractor
output_channel: 512 # the number of output channel of Feature extractor
hidden_size: 256 # the size of the LSTM hidden state

# Optimizer
lr: 0.001 # learning rate, 0.001 for Adam
weight_decay: 0.01 # weight decay, 0.01 for Adam

# Training
grad_clip: 5 # gradient clipping value
workers: 8 # number of data loading workers

# Experiment
manual_seed: 111 # for random seed setting
method: "DD" # select Domain Stratifying method, DD|HDGE
