# HDGE
decay_epoch: 100 # epoch from which to start lr decay
load_height: 48 # image height
load_width: 160 # image width
crop_height: 32 # image height to be cropped
crop_width: 100 # image width to be cropped
lamda: 10 # lamda for gradient penalty
idt_coef: 0.5 # coefficient for identity loss
ngf: 64 # of gen filters in first conv layer
ndf: 64 # of discrim filters in first conv layer
norm: "instance" # instance normalization or batch normalization

# Optimizer
lr: 0.001 # learning rate, 0.001 for Adam

# Training
workers: 8 # number of data loading workers

# Experiment
manual_seed: 111 # for random seed setting
method: "HDGE" # select Domain Stratifying method, DD|HDGE
